require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require 'pry'
require './lib/strong_renderer'
require './lib/list_renderer'
require './lib/link_renderer'
require './lib/link_detector'
require './lib/text_processor'
require './lib/header_renderer'
